### ISSUE TITLE
GLSLIFY style name 匹配问题

### ISSUE THREAD

**Issue by Randysheng** [sakitam-gis/vis-engine#1]
**Shader.ts** 中 `getShaderName` 相关正则 `/#define[\s*]SHADER_NAME[\s*]([\w-]+)[\s*]/` 是否应该改为 `/#define\s*SHADER_NAME\s*([\w-]+)\s*/`。**utils** 中 `getShaderName` 同理。

**Comment by sakitam-fdd** [comment]
@Randysheng  thank

![image](https://github.com/sakitam-gis/vis-engine/assets/19517451/095fcc5c-fe16-4604-b607-a652daeb4efc)

**Comment by sakitam-fdd** [comment]
@Randysheng close in v1.5.2，并且同步在 luma.gl 中报告了这个问题 [1923](https://github.com/visgl/luma.gl/issues/1923)
